= OData Spring Boot Starter {nbsp}image:https://maven-badges.herokuapp.com/maven-central/com.github.pukkaone/odata-web-spring-boot-starter/badge.svg[Maven Central,link="https://maven-badges.herokuapp.com/maven-central/com.github.pukkaone/odata-web-spring-boot-starter"]

Convenient dependency descriptors to add OData to your application.


== OData Elasticsearch Spring Boot Starter

This adds an OData endpoint which reads data from Elasticsearch.


=== Usage

Add this dependency to your Maven project:
[source,xml]
----
<dependency>
  <groupId>com.github.pukkaone</groupId>
  <artifactId>odata-elasticsearch-spring-boot-starter</artifactId>
  <version>${odata-spring-boot-starter.version}</version>
</dependency>
----

Set these application properties:
[source,yaml]
----
spring:
  elasticsearch:
    rest:
      uris: ELASTICSEARCH_REST_API_URI
----


=== Application Properties

Various properties can be specified inside your `application.properties` or `application.yml` file,
or as command line switches.

`odata.web.service-parent-path`::
OData service root URI will be
`${server.servlet.context-path}${odata.web.service-parent-path}/` _alias_or_index_name_ +
Default: `/odata`


=== Translating Elasticsearch to Entity Data Model

|===
| Elasticsearch | Entity Data Model | Name

| alias/index
| Namespace
| _alias_or_index_name_

| alias/index
| Schema
| _Namespace_

| alias/index
| Entity Container
| _alias_or_index_name_

| alias/index
| Entity Set
| _alias_or_index_name_

| alias/index
| Entity Type
| _Namespace_ `.` _alias_or_index_name_

| nested
| Collection(Complex Type)
| _Namespace_ `.` _nested_name_

| object
| Complex Type
| _Namespace_ `.` _object_name_
|===
